/**
 * Storage keys used to persist app state.
 * Keep these values unchanged to preserve compatibility
 * with existing saved data across app versions.
 */
export const STORAGE_KEY = "kiss-recorder-local-v3";
export const LANGUAGE_KEY = "kiss-recorder-language-local-v3";
export const ICON_COLOR_KEY = "kiss-recorder-icon-color-v1";
export const PEOPLE_FILE_NAME = "kiss-recorder-people.json";

// Main decorative asset displayed on the intro screen
export const MAIN_VISUAL_ASSET = "/assets/kiss-recorder-icon.png";

// Reusable option lists used across forms and analytics.
export const GENDERS = ["male", "female", "other"];
export const SCORE_OPTIONS = [0, 1, 2, 3, 4, 5];

// Centralized UI palette.
export const PALETTE = {
  bg: "#fff8fb",
  bgSoft: "#fff3f8",
  bgGradientFrom: "#ffddea",
  bgGradientVia: "#f8abc7",
  bgGradientTo: "#bde0fe",
  card: "#ffffff",
  cardSoft: "#fff7fb",
  rose: "#e27396",
  roseSoft: "#f8abc7",
  blush: "#ffddea",
  sky: "#bde0fe",
  sky2: "#a2d2ff",
  mint: "#eaf2d7",
  aqua: "#b3dee2",
  lilac: "#e9d1f0",
  lavender: "#cdb4db",
  deep: "#880d1e",
  deep2: "#3c096c",
  navy: "#3b3b6d",
  line: "#ead7e2",
  text: "#43384a",
  textSoft: "#6b6270",
};

// Generic colors for graphics.
export const CHART_COLORS = [
  "#e27396",
  "#a2d2ff",
  "#b3dee2",
  "#cdb4db",
  "#eaf2d7",
  "#f49cbb",
  "#b8c0ff",
  "#c8b6ff",
];

// Gender-specific colors.
export const GENDER_COLORS = {
  male: "#7aa7ff",
  female: "#e27396",
  other: "#8fc9b5",
};

// Zodiac sign options by language. Aquarius
export const ZODIAC_OPTIONS = {
  en: [
    "♒ Aquarius (January 20 - February 19)",
    "♓ Pisces (February 20 - March 20)",
    "♈ Aries (March 21 - April 19)",
    "♉ Taurus (April 20 - May 20)",
    "♊ Gemini (May 21 - June 20)",
    "♋ Cancer (June 21 - July 22)",
    "♌ Leo (July 23 - August 23)",
    "♍ Virgo (August 24 - September 22)",
    "♎ Libra (September 23 - October 22)",
    "♏ Scorpio (October 23 - November 21)",
    "♐ Sagittarius (November 22 - December 21)",
    "♑ Capricorn (December 22 - January 19)",
  ],
  es: [
    "♒ Acuario (20 enero - 19 febrero)",
    "♓ Piscis (20 febrero - 20 marzo)",
    "♈ Aries (21 marzo - 19 abril)",
    "♉ Tauro (20 abril - 20 mayo)",
    "♊ Géminis (21 mayo - 20 junio)",
    "♋ Cáncer (21 junio - 22 julio)",
    "♌ Leo (23 julio - 23 agosto)",
    "♍ Virgo (24 agosto - 22 septiembre)",
    "♎ Libra (23 septiembre - 22 octubre)",
    "♏ Escorpio (23 octubre - 21 noviembre)",
    "♐ Sagitario (22 noviembre - 21 diciembre)",
    "♑ Capricornio (22 diciembre - 19 enero)",
  ],
};

// List of texts in the app, organized by language.
export const COPY = {
  en: {
    appTitle: "KissRecorder",
    heroTitle: "KissRecorder",
    peopleSaved: "People saved",
    totalEvents: "Total events",
    addNewPerson: "Add new person",
    viewEditPeople: "View and edit people",
    viewStatistics: "View statistics",
    clearLocalData: "Clear local data",
    exportPdf: "Export PDF",
    pdfReady: "Summary & statistics report",
    home: "Home",
    add: "Add",
    people: "People",
    stats: "Stats",
    name: "Name",
    age: "Age",
    gender: "Gender",
    howWeMet: "How we met",
    zodiacSign: "Zodiac sign",
    activity: "Activity",
    detail: "Detail",
    savePerson: "Save person",
    saveInfo: "Save info",
    cancel: "Cancel",
    back: "Back",
    editPerson: "Edit person",
    updateDetails: "Update personal details and save changes.",
    requiredName: "Name is required.",
    requiredAge: "Age is required.",
    validAge: "Use a valid age.",
    requiredGender: "Gender is required.",
    requiredHowWeMet: "How you met is required.",
    requiredZodiac: "Zodiac sign is required.",
    requiredActivity: "Activity is required.",
    select: "Select",
    none: "None",
    studies: "studies",
    works: "works",
    studiesWorks: "studies and works",
    other: "other",
    male: "male",
    female: "female",
    personListTitle: "People",
    searchPlaceholder: "Search by name, detail, or event notes",
    filters: "Filters",
    refineList: "Refine people list",
    filtersOrg: "Filters & organization",
    refineResults: "Refine results and reorganize the list.",
    ageRange: "Age range",
    min: "Min",
    max: "Max",
    allActivities: "All activities",
    allSigns: "All signs",
    groupBy: "Group by",
    sortBy: "Sort by",
    groupName: "Name",
    groupLastEvent: "Last event date",
    sortName: "Name",
    sortFirst: "First event date",
    sortLast: "Last event date",
    resetFilters: "Reset filters",
    showingResults: "Showing",
    result: "result",
    results: "results",
    noPeopleFound: "No people found",
    tryDifferent: "Try a different search term or reset your filters.",
    clearSearch: "Clear search",
    years: "years",
    met: "Met",
    events: "events",
    last: "Last",
    delete: "Delete",
    addEvent: "Add event",
    eventHistory: "Event history",
    tapEvent: "Tap an event to edit it quickly.",
    deleteAll: "Delete all",
    noEventsYet: "No events recorded for this person yet.",
    noDetailsAdded: "No details added.",
    addEventTitle: "Add event",
    addEventDesc: "Record a new encounter.",
    editEventTitle: "Edit event",
    editEventDesc: "Update or remove this event.",
    eventDate: "Date",
    eventDetails: "Details",
    eventDetailsPlaceholder: "Optional context about the encounter",
    dateFormatHelper: "Required format: yyyy.MM.dd",
    validDateMsg: "Date must follow yyyy.MM.dd and be valid.",
    saveEvent: "Save event",
    deleteEvent: "Delete event",
    analyticsTitle: "Summary & statistics",
    analyticsDesc: "Explore trends in a clean, wrapped-style overview.",
    avgEvents: "Average events / person",
    acrossAll: "Across all saved people",
    topPerson: "Top person",
    eventsPerMonth: "Events per month",
    monthlyActivity: "Monthly encounter activity",
    eventsPerYear: "Events per year",
    yearlyTotals: "Yearly encounter totals",
    peopleMostEvents: "People with most events",
    topTracked: "Top tracked contacts",
    eventsByZodiac: "Events by zodiac sign",
    groupedBySign: "Total events grouped by sign",
    eventsByActivity: "Events by activity",
    groupedByActivity: "Total events grouped by person activity",
    personsByGender: "People by gender",
    eventsByGender: "Events by gender",
    personsByAge: "People by age",
    personsByFirstLetter: "People by first letter",
    eventsByPersonCount: "People count by event count",
    multiYearPeople: "People with events in multiple years",
    multiYearSubtitle: "Years shared per person",
    noMultiYearPeopleYet: "No people with events in multiple years yet",
    boxplotAgeRange: "Age range",
    noDataYet: "No data yet",
    language: "Language",
    settings: "Settings",
    hideStats: "Hide stats",
    showStats: "Show stats",
    english: "English",
    spanish: "Español",
    iconColor: "Icon color",
    colorGold: "Gold",
    colorBlue: "Blue",
    colorPink: "Pink",
    colorPurple: "Purple",
    noEvents: "No events",
    ungrouped: "Ungrouped",
    optionalActivityDetails:
      "Optional details about activity, routine, or context",
    hiddenAccess: "Open app",
    missingEventDetailsBadge: "Needs detail",
    genderSplit: "Distribution of saved people",
    eventsGenderSplit: "Total events grouped by gender",
    ageDistribution: "How many people are at each age",
    firstLetterDist: "First-letter grouping",
    eventCountBuckets: "How many people have the same event count",
    multiYearDesc: "People whose events span two or more years",
    yearOverlap: "Shared years",
    saveAndBack: "Save info",
    eventScore: "Kisses",
    kiss: "kiss",
    kisses: "kisses",
    scoreDistribution: "Kisses distribution",
    scoreDistributionDesc: "How events are rated with kisses",
    averageScore: "Average kisses / event",
    divideByYear: "Divide by year",
    showAllTogether: "Show all together",
    allYears: "All years",
    overview: "Overview",
    time: "Time",
    peopleStats: "People",
    scores: "Kisses",
    statsGroupOverview: "General summary",
    statsGroupTime: "Activity over time",
    statsGroupPeople: "Who appears most",
    statsGroupScores: "Kisses and ratings",
    noScore: "No kisses",
    reportGenerated: "Generated from KissRecorder",
    clearDataConfirmTitle: "Delete all data?",
    clearDataConfirmDesc:
      "This will permanently delete all saved people and events. This action cannot be undone.",
    clearDataConfirmAction: "Delete everything",
    pdfSuccessTitle: "PDF exported",
    pdfSuccessDesc: "Your report has been saved successfully.",
    pdfErrorTitle: "Export failed",
    pdfErrorDesc: "Something went wrong while generating the PDF.",
    pdfEmptyTitle: "No data to export",
    pdfEmptyDesc: "You need at least one person and one event to export statistics.",
    savePdfErrorLog: "Save error log",
    close: "Close",
  },
  es: {
    appTitle: "KissRecorder",
    heroTitle: "KissRecorder",
    peopleSaved: "Personas guardadas",
    totalEvents: "Eventos totales",
    addNewPerson: "Agregar persona",
    viewEditPeople: "Ver y editar personas",
    viewStatistics: "Ver estadísticas",
    clearLocalData: "Borrar datos",
    exportPdf: "Exportar PDF",
    pdfReady: "Resumen y reporte de estadísticas",
    home: "Inicio",
    add: "Agregar",
    people: "Personas",
    stats: "Estadísticas",
    name: "Nombre",
    age: "Edad",
    gender: "Género",
    howWeMet: "Cómo nos conocimos",
    zodiacSign: "Signo zodiacal",
    activity: "Actividad",
    detail: "Detalle",
    savePerson: "Guardar persona",
    saveInfo: "Guardar info",
    cancel: "Cancelar",
    back: "Volver",
    editPerson: "Editar persona",
    updateDetails: "Actualiza los datos personales y guarda los cambios.",
    requiredName: "El nombre es obligatorio.",
    requiredAge: "La edad es obligatoria.",
    validAge: "Usa una edad válida.",
    requiredGender: "El género es obligatorio.",
    requiredHowWeMet: "Cómo se conocieron es obligatorio.",
    requiredZodiac: "El signo zodiacal es obligatorio.",
    requiredActivity: "La actividad es obligatoria.",
    select: "Seleccionar",
    none: "Ninguno",
    studies: "estudia",
    works: "trabaja",
    studiesWorks: "estudia y trabaja",
    other: "otro",
    male: "masculino",
    female: "femenino",
    personListTitle: "Personas",
    searchPlaceholder: "Buscar por nombre, detalle o notas de eventos",
    filters: "Filtros",
    refineList: "Refinar lista",
    filtersOrg: "Filtros y organización",
    refineResults: "Refina resultados y reorganiza la lista.",
    ageRange: "Rango de edad",
    min: "Mín.",
    max: "Máx.",
    allActivities: "Todas las actividades",
    allSigns: "Todos los signos",
    groupBy: "Agrupar por",
    sortBy: "Ordenar por",
    groupName: "Nombre",
    groupLastEvent: "Último evento",
    sortName: "Nombre",
    sortFirst: "Primer evento",
    sortLast: "Último evento",
    resetFilters: "Restablecer filtros",
    showingResults: "Mostrando",
    result: "resultado",
    results: "resultados",
    noPeopleFound: "No se encontraron personas",
    tryDifferent: "Prueba otra búsqueda o restablece los filtros.",
    clearSearch: "Limpiar búsqueda",
    years: "años",
    met: "Nos conocimos",
    events: "eventos",
    last: "Último",
    delete: "Eliminar",
    addEvent: "Agregar evento",
    eventHistory: "Historial de eventos",
    tapEvent: "Toca un evento para editarlo rápidamente.",
    deleteAll: "Eliminar todos",
    noEventsYet: "Todavía no hay eventos registrados para esta persona.",
    noDetailsAdded: "No se añadieron detalles.",
    addEventTitle: "Agregar evento",
    addEventDesc: "Registra un nuevo encuentro.",
    editEventTitle: "Editar evento",
    editEventDesc: "Actualiza o elimina este evento.",
    eventDate: "Fecha",
    eventDetails: "Detalles",
    eventDetailsPlaceholder: "Contexto opcional sobre el encuentro",
    dateFormatHelper: "Formato obligatorio: yyyy.MM.dd",
    validDateMsg: "La fecha debe seguir el formato yyyy.MM.dd y ser válida.",
    saveEvent: "Guardar evento",
    deleteEvent: "Eliminar evento",
    analyticsTitle: "Resumen y estadísticas",
    analyticsDesc:
      "Explora tendencias de tus encuentros en un resumen estilo wrapped.",
    avgEvents: "Promedio de eventos / persona",
    acrossAll: "Entre todas las personas guardadas",
    topPerson: "Persona principal",
    eventsPerMonth: "Eventos por mes",
    monthlyActivity: "Actividad mensual de encuentros",
    eventsPerYear: "Eventos por año",
    yearlyTotals: "Totales anuales de encuentros",
    peopleMostEvents: "Personas con más eventos",
    topTracked: "Contactos con más registros",
    eventsByZodiac: "Eventos por signo zodiacal",
    groupedBySign: "Eventos totales agrupados por signo",
    eventsByActivity: "Eventos por actividad",
    groupedByActivity: "Eventos totales agrupados por actividad",
    personsByGender: "Personas por género",
    eventsByGender: "Eventos por género",
    personsByAge: "Personas por edad",
    personsByFirstLetter: "Personas por inicial",
    eventsByPersonCount: "Cantidad de personas por cantidad de eventos",
    multiYearPeople: "Personas con eventos en múltiples años",
    multiYearSubtitle: "Años compartidos por persona",
    noMultiYearPeopleYet:
      "Todavía no hay personas con eventos en múltiples años",
    boxplotAgeRange: "Rango de edades",
    noDataYet: "Todavía no hay datos",
    language: "Idioma",
    settings: "Configuración",
    hideStats: "Ocultar estadísticas",
    showStats: "Mostrar estadísticas",
    english: "English",
    spanish: "Español",
    iconColor: "Color del ícono",
    colorGold: "Dorado",
    colorBlue: "Azul",
    colorPink: "Rosa",
    colorPurple: "Morado",
    noEvents: "Sin eventos",
    ungrouped: "Sin grupo",
    optionalActivityDetails:
      "Detalles opcionales sobre actividad, rutina o contexto",
    hiddenAccess: "Abrir app",
    missingEventDetailsBadge: "Falta detalle",
    genderSplit: "Distribución de personas guardadas",
    eventsGenderSplit: "Eventos totales agrupados por género",
    ageDistribution: "Cuántas personas hay en cada edad",
    firstLetterDist: "Agrupación por inicial",
    eventCountBuckets: "Cuántas personas tienen la misma cantidad de eventos",
    multiYearDesc: "Personas cuyos eventos abarcan dos o más años",
    yearOverlap: "Años compartidos",
    saveAndBack: "Guardar info",
    eventScore: "Besos",
    kiss: "beso",
    kisses: "besos",
    scoreDistribution: "Distribución de besos",
    scoreDistributionDesc: "Cómo se califican los eventos con besos",
    averageScore: "Promedio de besos / evento",
    divideByYear: "Dividir por año",
    showAllTogether: "Mostrar todo junto",
    allYears: "Todos los años",
    overview: "Resumen",
    time: "Tiempo",
    peopleStats: "Personas",
    scores: "Besos",
    statsGroupOverview: "Resumen general",
    statsGroupTime: "Actividad en el tiempo",
    statsGroupPeople: "Quién aparece más",
    statsGroupScores: "Besos y calificaciones",
    noScore: "Sin besos",
    reportGenerated: "Generado desde KissRecorder",
    clearDataConfirmTitle: "¿Eliminar todos los datos?",
    clearDataConfirmDesc:
      "Se eliminarán definitivamente todas las personas y eventos guardados. Esta acción no se puede deshacer.",
    clearDataConfirmAction: "Eliminar todo",
    pdfSuccessTitle: "PDF exportado",
    pdfSuccessDesc: "Tu informe se ha guardado correctamente.",
    pdfErrorTitle: "Error al exportar",
    pdfErrorDesc: "Ocurrió un error al generar el PDF.",
    pdfEmptyTitle: "Sin datos para exportar",
    pdfEmptyDesc: "Necesitas al menos una persona y un evento para exportar estadísticas.",
    savePdfErrorLog: "Guardar registro de error",
    close: "Cerrar",
  },
};
