/**
 * Storage keys used to persist app state.
 * Keep these values unchanged to preserve compatibility
 * with existing saved data across app versions.
 */
export const STORAGE_KEY = "kiss-recorder-local-v3";
export const LANGUAGE_KEY = "kiss-recorder-language-local-v3";
export const ICON_COLOR_KEY = "kiss-recorder-icon-color-v1";
export const PEOPLE_FILE_NAME = "kiss-recorder-people.json";
export const SETTINGS_FILE_NAME = "kiss-recorder-settings.json";

// Main decorative asset displayed on the intro screen
export const MAIN_VISUAL_ASSET = "/assets/kiss-recorder-icon.png";

// Reusable option lists used across forms and analytics.
export const GENDERS = ["male", "female", "other"];
export const SCORE_OPTIONS = [0, 1, 2, 3, 4, 5];

// Centralized UI palette.
export const PALETTE = {
  bg: "#fff8fb",
  bgSoft: "#fff3f8",
  bgGradientFrom: "#ffddea",
  bgGradientVia: "#f8abc7",
  bgGradientTo: "#bde0fe",
  card: "#ffffff",
  cardSoft: "#fff7fb",
  rose: "#e27396",
  roseSoft: "#f8abc7",
  blush: "#ffddea",
  sky: "#bde0fe",
  sky2: "#a2d2ff",
  mint: "#eaf2d7",
  aqua: "#b3dee2",
  lilac: "#e9d1f0",
  lavender: "#cdb4db",
  deep: "#880d1e",
  deep2: "#3c096c",
  navy: "#3b3b6d",
  line: "#ead7e2",
  text: "#43384a",
  textSoft: "#6b6270",
  // Structural surfaces and borders
  inputBorder: "#ecd6e0",
  cardBorder: "#f1dde7",
  innerCardBorder: "#efdee6",
  inputBg: "rgba(255,255,255,0.88)",
  controlBg: "rgba(255,255,255,0.86)",
  cardBg: "rgba(255,255,255,0.82)",
  surfaceBg: "rgba(255,255,255,0.78)",
};

// Semantic text scale. Spread into style objects or use directly as style prop.
export const TEXT = {
  caption:    { fontSize: "0.75rem",  lineHeight: "1rem"    },
  label:      { fontSize: "0.75rem",  lineHeight: "1rem",    fontWeight: "600" },
  input:      { fontSize: "0.8rem"                          },
  body:       { fontSize: "0.875rem", lineHeight: "1.25rem" },
  bodyStrong: { fontSize: "0.875rem", lineHeight: "1.25rem", fontWeight: "600" },
  base:       { fontSize: "1rem",     lineHeight: "1.5rem"  },
  title:      { fontSize: "1rem",     lineHeight: "1.5rem",  fontWeight: "600" },
  subheading: { fontSize: "1.125rem", lineHeight: "1.75rem", fontWeight: "700" },
  heading:    { fontSize: "1.5rem",   lineHeight: "2rem",    fontWeight: "700" },
};

// Generic colors for graphics.
export const CHART_COLORS = [
  "#e27396",
  "#a2d2ff",
  "#b3dee2",
  "#cdb4db",
  "#eaf2d7",
  "#f49cbb",
  "#b8c0ff",
  "#c8b6ff",
];

// Gender-specific colors.
export const GENDER_COLORS = {
  male: "#7aa7ff",
  female: "#e27396",
  other: "#8fc9b5",
};

const MONTH_ABBR = {
  January: "Jan", February: "Feb", March: "Mar", April: "Apr",
  May: "May", June: "Jun", July: "Jul", August: "Aug",
  September: "Sep", October: "Oct", November: "Nov", December: "Dec",
  enero: "ene", febrero: "feb", marzo: "mar", abril: "abr",
  mayo: "may", junio: "jun", julio: "jul", agosto: "ago",
  septiembre: "sep", octubre: "oct", noviembre: "nov", diciembre: "dic",
};

export function abbreviateZodiacMonths(zodiacString) {
  return zodiacString.replace(
    /January|February|March|April|May|June|July|August|September|October|November|December|enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre/g,
    (m) => MONTH_ABBR[m] ?? m,
  );
}

// Zodiac sign options by language. Aquarius
export const ZODIAC_OPTIONS = {
  en: [
    "♒ Aquarius (January 20 - February 19)",
    "♓ Pisces (February 20 - March 20)",
    "♈ Aries (March 21 - April 19)",
    "♉ Taurus (April 20 - May 20)",
    "♊ Gemini (May 21 - June 20)",
    "♋ Cancer (June 21 - July 22)",
    "♌ Leo (July 23 - August 23)",
    "♍ Virgo (August 24 - September 22)",
    "♎ Libra (September 23 - October 22)",
    "♏ Scorpio (October 23 - November 21)",
    "♐ Sagittarius (November 22 - December 21)",
    "♑ Capricorn (December 22 - January 19)",
  ],
  es: [
    "♒ Acuario (20 enero - 19 febrero)",
    "♓ Piscis (20 febrero - 20 marzo)",
    "♈ Aries (21 marzo - 19 abril)",
    "♉ Tauro (20 abril - 20 mayo)",
    "♊ Géminis (21 mayo - 20 junio)",
    "♋ Cáncer (21 junio - 22 julio)",
    "♌ Leo (23 julio - 23 agosto)",
    "♍ Virgo (24 agosto - 22 septiembre)",
    "♎ Libra (23 septiembre - 22 octubre)",
    "♏ Escorpio (23 octubre - 21 noviembre)",
    "♐ Sagitario (22 noviembre - 21 diciembre)",
    "♑ Capricornio (22 diciembre - 19 enero)",
  ],
};

// List of texts in the app, organized by language.
export const COPY = {
  en: {
    appTitle: "KissRecorder",
    heroTitle: "KissRecorder",
    peopleSaved: "People saved",
    totalEvents: "Total events",
    addNewPerson: "Add new person",
    viewEditPeople: "View and edit people",
    viewStatistics: "View statistics",
    clearLocalData: "Clear local data",
    clearLocalDataLabel: "Clear",
    exportJson: "Export data",
    exportJsonLabel: "Export",
    importJson: "Import data",
    importJsonLabel: "Import",
    dataSection: "Data",
    importJsonConfirmTitle: "Add imported data?",
    importJsonConfirmPeople: "people found in file",
    importJsonConfirmNew: "new people to add",
    importJsonConfirmSkipped: "already in your data (will be skipped)",
    importJsonConfirmAction: "Import",
    importJsonSuccessTitle: "Data imported",
    importJsonSuccessDesc: "people added to your data.",
    importJsonEmptyTitle: "No new people found",
    importJsonEmptyDesc: "All people in this file are already in your data.",
    importJsonErrorTypeTitle: "Invalid file type",
    importJsonErrorTypeDesc: "Please select a .json file.",
    importJsonErrorFormatTitle: "Invalid data format",
    importJsonErrorFormatDesc: "The file does not match the expected format. Make sure it was exported from KissRecorder.",
    exportJsonSuccessTitle: "Data exported",
    exportJsonSuccessWithWarningsTitle: "Exported with missing fields",
    exportJsonSuccessWithWarningsDesc: "Some required fields were missing and were exported as empty values.",
    exportJsonSavedAs: "Saved as",
    exportJsonLocationNative: "Saved to external storage",
    exportJsonLocationWeb: "Saved to your Downloads folder",
    exportJsonErrorTitle: "Export failed",
    exportJsonErrorDesc: "Something went wrong while exporting your data.",
    saveJsonErrorLog: "Save error log",
    exportPdf: "Export PDF",
    pdfReady: "Summary & statistics report",
    home: "Home",
    add: "Add",
    people: "People",
    stats: "Stats",
    name: "Name",
    age: "Age",
    gender: "Gender",
    howWeMet: "How we met",
    zodiacSign: "Zodiac sign",
    activity: "Activity",
    detail: "Specific",
    savePerson: "Save person",
    saveInfo: "Save info",
    cancel: "Cancel",
    back: "Back",
    editPerson: "Edit person",
    updateDetails: "Update personal details and save changes.",
    requiredName: "Name is required.",
    requiredAge: "Age is required.",
    validAge: "Use a valid age.",
    requiredGender: "Gender is required.",
    requiredHowWeMet: "How you met is required.",
    requiredZodiac: "Zodiac sign is required.",
    requiredActivity: "Activity is required.",
    select: "Select",
    none: "None",
    studies: "studies",
    works: "works",
    studiesWorks: "studies and works",
    other: "other",
    studiesForm: "study",
    worksForm: "work",
    studiesWorksForm: "study and work",
    male: "male",
    female: "female",
    personListTitle: "People",
    searchPlaceholder: "Search by name, detail, or event notes",
    filters: "Filters",
    refineList: "Filter list",
    filtersOrg: "Filters & organization",
    refineResults: "Refine results and reorganize the list.",
    ageRange: "Age range",
    min: "Min",
    max: "Max",
    allActivities: "All activities",
    allSigns: "All signs",
    groupBy: "Group by",
    sortBy: "Sort by",
    groupName: "Name",
    groupLastEvent: "Last event date",
    sortName: "Name",
    sortFirst: "First event date",
    sortLast: "Last event date",
    eventDateRange: "Event date range",
    dateFrom: "From",
    dateTo: "To",
    resetFilters: "Reset filters",
    showingResults: "Showing",
    result: "result",
    results: "results",
    noPeopleFound: "No people found",
    tryDifferent: "Try a different search term or reset your filters.",
    clearSearch: "Clear search",
    years: "years",
    met: "Met",
    events: "events",
    last: "Last",
    delete: "Delete",
    deletePerson: "Delete person",
    addEvent: "Add event",
    eventHistory: "Event history",
    tapEvent: "Tap an event to edit it quickly.",
    deleteAll: "Delete all",
    deleteAllEvents: "Delete all events",
    deleteAllEventsConfirmTitle: "Delete all events?",
    deleteAllEventsConfirmDesc: "This will permanently remove all events for this person. This action cannot be undone.",
    deleteAllEventsConfirmAction: "Yes, delete all",
    deletePersonConfirmTitle: "Delete this person?",
    deletePersonConfirmDesc: "This will permanently delete this person and all their events. This action cannot be undone.",
    deletePersonConfirmAction: "Yes, delete",
    noEventsYet: "No events recorded for this person yet.",
    noDetailsAdded: "No details added.",
    addEventTitle: "Add event",
    addEventDesc: "Record a new encounter.",
    editEventTitle: "Edit event",
    editEventDesc: "Update or remove this event.",
    eventDate: "Date",
    eventDetails: "Details",
    eventDetailsPlaceholder: "Optional context about the encounter",
    dateFormatHelper: "Required format: yyyy.MM.dd",
    validDateMsg: "Date must follow yyyy.MM.dd and be valid.",
    futureDateMsg: "Date cannot be in the future.",
    saveEvent: "Save event",
    deleteEvent: "Delete event",
    deleteEventConfirmTitle: "Delete this event?",
    deleteEventConfirmDesc: "This action cannot be undone.",
    deleteEventConfirmAction: "Yes, delete",
    analyticsTitle: "Summary & statistics",
    analyticsDesc: "Explore trends in a clean, wrapped-style overview.",
    avgEvents: "Average events / person",
    acrossAll: "Across all saved people",
    topPerson: "Person with most events",
    topPersonPlural: "People with most events",
    tiedForTop: "at the top",
    eventsPerMonth: "Events per month",
    monthlyActivity: "Monthly encounter activity",
    eventsPerYear: "Events per year",
    yearlyTotals: "Yearly encounter totals",
    peopleMostEvents: "People with most events",
    topTracked: "Top tracked contacts",
    eventsByZodiac: "Events by zodiac sign",
    groupedBySign: "Total events grouped by sign",
    personsByZodiac: "People by zodiac sign",
    zodiacDistribution: "Distribution of people across signs",
    eventsByActivity: "Events by activity",
    groupedByActivity: "Total events grouped by person activity",
    personsByActivity: "People by activity",
    activityDistribution: "Distribution of people across activities",
    personsByGender: "People by gender",
    eventsByGender: "Events by gender",
    personsByAge: "People by age",
    personsByFirstLetter: "People by first letter",
    eventsByPersonCount: "People count by event count",
    multiYearPeople: "People with events in multiple years",
    multiYearSubtitle: "Years shared per person",
    noMultiYearPeopleYet: "No people with events in multiple years yet",
    dumbbellChart: "Presence by year",
    dumbbellDesc: "Years each person appears in — dots connected when consecutive",
    heatmapChart: "Activity heatmap",
    heatmapDesc: "Number of events per person per year",
    boxplotAgeRange: "Age range",
    noDataYet: "No data yet",
    chartEvent: "event",
    chartEvents: "events",
    chartPerson: "person",
    chartPersons: "people",
    chartYear: "year",
    language: "Language",
    settings: "Settings",
    hideStats: "Hide stats",
    showStats: "Show stats",
    english: "English",
    spanish: "Español",
    iconColor: "Icon color",
    colorYellow: "Yellow",
    colorBlue: "Blue",
    colorPink: "Pink",
    colorPurple: "Purple",
    noEvents: "No events",
    ungrouped: "Ungrouped",
    specificStudies: "What do you study?",
    specificWorks: "What do you do for work? If you studied something, mention what",
    specificStudiesWorks: "What do you study and what do you do for work?",
    optionalActivityDetails:
      "Optional details about activity, routine, or context",
    hiddenAccess: "Open app",
    missingEventDetailsBadge: "Needs detail",
    genderSplit: "Distribution of saved people",
    eventsGenderSplit: "Total events grouped by gender",
    ageDistribution: "How many people are at each age",
    firstLetterDist: "First-letter grouping",
    eventCountBuckets: "How many people have the same event count",
    multiYearDesc: "People whose events span two or more years",
    yearOverlap: "Shared years",
    saveAndBack: "Save info",
    eventScore: "Rating",
    kiss: "kiss",
    kisses: "kisses",
    eventPlace: "Place",
    eventPlacePlaceholder: "Where did it happen?",
    eventSituation: "Situation",
    eventSituationPlaceholder: "What was the context?",
    eventObservations: "Observations",
    eventObservationsPlaceholder: "Optional additional notes",
    requiredPlace: "Place is required.",
    requiredSituation: "Situation is required.",
    scoreDistribution: "Rating distribution",
    scoreDistributionDesc: "How events are rated",
    averageScore: "Average rating / event",
    divideByYear: "Divide by year",
    showAllTogether: "Show all together",
    allYears: "All years",
    overview: "Overview",
    time: "Time",
    peopleStats: "People",
    scores: "Ratings",
    statsGroupOverview: "General summary",
    statsGroupTime: "Activity over time",
    statsGroupPeople: "Who appears most",
    statsGroupScores: "Ratings",
    noScore: "No rating",
    reportGenerated: "Generated from KissRecorder",
    clearDataConfirmTitle: "Delete all data?",
    clearDataConfirmDesc:
      "This will permanently delete all saved people and events. This action cannot be undone.",
    clearDataConfirmAction: "Delete everything",
    pdfSuccessTitle: "PDF exported",
    pdfSuccessDesc: "Your report has been saved successfully.",
    pdfErrorTitle: "Export failed",
    pdfErrorDesc: "Something went wrong while generating the PDF.",
    pdfEmptyTitle: "No data to export",
    pdfEmptyDesc: "You need at least one person and one event to export statistics.",
    savePdfErrorLog: "Save error log",
    close: "Close",
  },
  es: {
    appTitle: "KissRecorder",
    heroTitle: "KissRecorder",
    peopleSaved: "Personas guardadas",
    totalEvents: "Eventos totales",
    addNewPerson: "Agregar persona",
    viewEditPeople: "Ver y editar personas",
    viewStatistics: "Ver estadísticas",
    clearLocalData: "Borrar datos",
    clearLocalDataLabel: "Borrar",
    exportJson: "Exportar datos",
    exportJsonLabel: "Exportar",
    importJson: "Importar datos",
    importJsonLabel: "Importar",
    dataSection: "Datos",
    importJsonConfirmTitle: "¿Agregar datos importados?",
    importJsonConfirmPeople: "personas encontradas en el archivo",
    importJsonConfirmNew: "personas nuevas a agregar",
    importJsonConfirmSkipped: "ya están en tus datos (se omitirán)",
    importJsonConfirmAction: "Importar",
    importJsonSuccessTitle: "Datos importados",
    importJsonSuccessDesc: "personas agregadas a tus datos.",
    importJsonEmptyTitle: "Sin personas nuevas",
    importJsonEmptyDesc: "Todas las personas de este archivo ya están en tus datos.",
    importJsonErrorTypeTitle: "Tipo de archivo inválido",
    importJsonErrorTypeDesc: "Selecciona un archivo .json.",
    importJsonErrorFormatTitle: "Formato de datos inválido",
    importJsonErrorFormatDesc: "El archivo no coincide con el formato esperado. Asegúrate de que fue exportado desde KissRecorder.",
    exportJsonSuccessTitle: "Datos exportados",
    exportJsonSuccessWithWarningsTitle: "Exportado con campos faltantes",
    exportJsonSuccessWithWarningsDesc: "Algunos campos obligatorios faltaban y se exportaron como valores vacíos.",
    exportJsonSavedAs: "Guardado como",
    exportJsonLocationNative: "Guardado en almacenamiento externo",
    exportJsonLocationWeb: "Guardado en tu carpeta de Descargas",
    exportJsonErrorTitle: "Error al exportar",
    exportJsonErrorDesc: "Ocurrió un error al exportar los datos.",
    saveJsonErrorLog: "Guardar registro de error",
    exportPdf: "Exportar PDF",
    pdfReady: "Resumen y reporte de estadísticas",
    home: "Inicio",
    add: "Agregar",
    people: "Personas",
    stats: "Estadísticas",
    name: "Nombre",
    age: "Edad",
    gender: "Género",
    howWeMet: "Cómo nos conocimos",
    zodiacSign: "Signo zodiacal",
    activity: "Actividad",
    detail: "Específica",
    savePerson: "Guardar persona",
    saveInfo: "Guardar info",
    cancel: "Cancelar",
    back: "Volver",
    editPerson: "Editar persona",
    updateDetails: "Actualiza los datos personales y guarda los cambios.",
    requiredName: "El nombre es obligatorio.",
    requiredAge: "La edad es obligatoria.",
    validAge: "Usa una edad válida.",
    requiredGender: "El género es obligatorio.",
    requiredHowWeMet: "Cómo se conocieron es obligatorio.",
    requiredZodiac: "El signo zodiacal es obligatorio.",
    requiredActivity: "La actividad es obligatoria.",
    select: "Seleccionar",
    none: "Ninguno",
    studies: "estudia",
    works: "trabaja",
    studiesWorks: "estudia y trabaja",
    other: "otro",
    studiesForm: "estudio",
    worksForm: "trabajo",
    studiesWorksForm: "estudio y trabajo",
    male: "masculino",
    female: "femenino",
    personListTitle: "Personas",
    searchPlaceholder: "Buscar por nombre, detalle o notas de eventos",
    filters: "Filtros",
    refineList: "Filtrar lista",
    filtersOrg: "Filtros y organización",
    refineResults: "Refina resultados y reorganiza la lista.",
    ageRange: "Rango de edad",
    min: "Mín.",
    max: "Máx.",
    allActivities: "Todas las actividades",
    allSigns: "Todos los signos",
    groupBy: "Agrupar por",
    sortBy: "Ordenar por",
    groupName: "Nombre",
    groupLastEvent: "Último evento",
    sortName: "Nombre",
    sortFirst: "Primer evento",
    sortLast: "Último evento",
    eventDateRange: "Rango de fecha de eventos",
    dateFrom: "Desde",
    dateTo: "Hasta",
    resetFilters: "Restablecer filtros",
    showingResults: "Mostrando",
    result: "resultado",
    results: "resultados",
    noPeopleFound: "No se encontraron personas",
    tryDifferent: "Prueba otra búsqueda o restablece los filtros.",
    clearSearch: "Limpiar búsqueda",
    years: "años",
    met: "Nos conocimos",
    events: "eventos",
    last: "Último",
    delete: "Eliminar",
    deletePerson: "Eliminar persona",
    addEvent: "Agregar evento",
    eventHistory: "Historial de eventos",
    tapEvent: "Toca un evento para editarlo rápidamente.",
    deleteAll: "Eliminar todos",
    deleteAllEvents: "Eliminar todos los eventos",
    deleteAllEventsConfirmTitle: "¿Eliminar todos los eventos?",
    deleteAllEventsConfirmDesc: "Esto eliminará permanentemente todos los eventos de esta persona. Esta acción no se puede deshacer.",
    deleteAllEventsConfirmAction: "Sí, eliminar todos",
    deletePersonConfirmTitle: "¿Eliminar esta persona?",
    deletePersonConfirmDesc: "Esto eliminará permanentemente a esta persona y todos sus eventos. Esta acción no se puede deshacer.",
    deletePersonConfirmAction: "Sí, eliminar",
    noEventsYet: "Todavía no hay eventos registrados para esta persona.",
    noDetailsAdded: "No se añadieron detalles.",
    addEventTitle: "Agregar evento",
    addEventDesc: "Registra un nuevo encuentro.",
    editEventTitle: "Editar evento",
    editEventDesc: "Actualiza o elimina este evento.",
    eventDate: "Fecha",
    eventDetails: "Detalles",
    eventDetailsPlaceholder: "Contexto opcional sobre el encuentro",
    dateFormatHelper: "Formato obligatorio: yyyy.MM.dd",
    validDateMsg: "La fecha debe seguir el formato yyyy.MM.dd y ser válida.",
    futureDateMsg: "La fecha no puede ser futura.",
    saveEvent: "Guardar evento",
    deleteEvent: "Eliminar evento",
    deleteEventConfirmTitle: "¿Eliminar este evento?",
    deleteEventConfirmDesc: "Esta acción no se puede deshacer.",
    deleteEventConfirmAction: "Sí, eliminar",
    analyticsTitle: "Resumen y estadísticas",
    analyticsDesc:
      "Explora tendencias de tus encuentros en un resumen estilo wrapped.",
    avgEvents: "Promedio de eventos / persona",
    acrossAll: "Entre todas las personas guardadas",
    topPerson: "Persona con más eventos",
    topPersonPlural: "Personas con más eventos",
    tiedForTop: "en el top",
    eventsPerMonth: "Eventos por mes",
    monthlyActivity: "Actividad mensual de encuentros",
    eventsPerYear: "Eventos por año",
    yearlyTotals: "Totales anuales de encuentros",
    peopleMostEvents: "Personas con más eventos",
    topTracked: "Contactos con más registros",
    eventsByZodiac: "Eventos por signo zodiacal",
    groupedBySign: "Eventos totales agrupados por signo",
    personsByZodiac: "Personas por signo zodiacal",
    zodiacDistribution: "Distribución de personas por signo",
    eventsByActivity: "Eventos por actividad",
    groupedByActivity: "Eventos totales agrupados por actividad",
    personsByActivity: "Personas por actividad",
    activityDistribution: "Distribución de personas por actividad",
    personsByGender: "Personas por género",
    eventsByGender: "Eventos por género",
    personsByAge: "Personas por edad",
    personsByFirstLetter: "Personas por inicial",
    eventsByPersonCount: "Cantidad de personas por cantidad de eventos",
    multiYearPeople: "Personas con eventos en múltiples años",
    multiYearSubtitle: "Años compartidos por persona",
    noMultiYearPeopleYet:
      "Todavía no hay personas con eventos en múltiples años",
    dumbbellChart: "Presencia por año",
    dumbbellDesc: "Años en los que aparece cada persona — puntos unidos si son consecutivos",
    heatmapChart: "Mapa de actividad",
    heatmapDesc: "Cantidad de eventos por persona por año",
    boxplotAgeRange: "Rango de edades",
    noDataYet: "Todavía no hay datos",
    chartEvent: "evento",
    chartEvents: "eventos",
    chartPerson: "persona",
    chartPersons: "personas",
    chartYear: "año",
    language: "Idioma",
    settings: "Configuración",
    hideStats: "Ocultar estadísticas",
    showStats: "Mostrar estadísticas",
    english: "English",
    spanish: "Español",
    iconColor: "Color del ícono",
    colorYellow: "Amarillo",
    colorBlue: "Azul",
    colorPink: "Rosa",
    colorPurple: "Morado",
    noEvents: "Sin eventos",
    ungrouped: "Sin grupo",
    specificStudies: "Qué estudias?",
    specificWorks: "En qué trabajas? Si estudiaste algo, menciona qué",
    specificStudiesWorks: "Qué estudias y en qué trabajas?",
    optionalActivityDetails:
      "Detalles opcionales sobre actividad, rutina o contexto",
    hiddenAccess: "Abrir app",
    missingEventDetailsBadge: "Falta detalle",
    genderSplit: "Distribución de personas guardadas",
    eventsGenderSplit: "Eventos totales agrupados por género",
    ageDistribution: "Cuántas personas hay en cada edad",
    firstLetterDist: "Agrupación por inicial",
    eventCountBuckets: "Cuántas personas tienen la misma cantidad de eventos",
    multiYearDesc: "Personas cuyos eventos abarcan dos o más años",
    yearOverlap: "Años compartidos",
    saveAndBack: "Guardar info",
    eventScore: "Calificación",
    kiss: "beso",
    kisses: "besos",
    eventPlace: "Lugar",
    eventPlacePlaceholder: "Dónde sucedió?",
    eventSituation: "Situación",
    eventSituationPlaceholder: "Cuál fue el contexto?",
    eventObservations: "Observaciones",
    eventObservationsPlaceholder: "Notas adicionales opcionales",
    requiredPlace: "El lugar es obligatorio.",
    requiredSituation: "La situación es obligatoria.",
    scoreDistribution: "Distribución de calificaciones",
    scoreDistributionDesc: "Cómo se califican los eventos",
    averageScore: "Promedio de calificación / evento",
    divideByYear: "Dividir por año",
    showAllTogether: "Mostrar todo junto",
    allYears: "Todos los años",
    overview: "Resumen",
    time: "Tiempo",
    peopleStats: "Personas",
    scores: "Calificaciones",
    statsGroupOverview: "Resumen general",
    statsGroupTime: "Actividad en el tiempo",
    statsGroupPeople: "Quién aparece más",
    statsGroupScores: "Calificaciones",
    noScore: "Sin calificación",
    reportGenerated: "Generado desde KissRecorder",
    clearDataConfirmTitle: "¿Eliminar todos los datos?",
    clearDataConfirmDesc:
      "Se eliminarán definitivamente todas las personas y eventos guardados. Esta acción no se puede deshacer.",
    clearDataConfirmAction: "Eliminar todo",
    pdfSuccessTitle: "PDF exportado",
    pdfSuccessDesc: "Tu informe se ha guardado correctamente.",
    pdfErrorTitle: "Error al exportar",
    pdfErrorDesc: "Ocurrió un error al generar el PDF.",
    pdfEmptyTitle: "Sin datos para exportar",
    pdfEmptyDesc: "Necesitas al menos una persona y un evento para exportar estadísticas.",
    savePdfErrorLog: "Guardar registro de error",
    close: "Cerrar",
  },
};
