/**
 * Storage keys used to persist app state.
 * Keep these values unchanged to preserve compatibility
 * with existing saved data across app versions.
 */
export const STORAGE_KEY = "kiss-recorder-local-v3";
export const LANGUAGE_KEY = "kiss-recorder-language-local-v3";
export const ICON_COLOR_KEY = "kiss-recorder-icon-color-v1";
export const THEME_KEY = "kiss-recorder-theme-v1";
export const STATS_VISIBLE_KEY = "kiss-recorder-stats-visible-v1";
export const SITUATION_TAGS_KEY = "kiss-recorder-situation-tags-v1";
export const PLACE_TAGS_KEY = "kiss-recorder-place-tags-v1";
export const ONBOARDING_DONE_KEY = "kiss-recorder-onboarding-done-v1";
export const ONBOARDING_VERSION_KEY = "kiss-recorder-onboarding-version-v1";
export const ONBOARDING_VERSION = 2;
export const PEOPLE_FILE_NAME = "kiss-recorder-people.json";
export const SETTINGS_FILE_NAME = "kiss-recorder-settings.json";

// Main decorative asset displayed on the intro screen
export const MAIN_VISUAL_ASSET = "/assets/kiss-recorder-icon.png";

// Reusable option lists used across forms and analytics.
export const GENDERS = ["male", "female", "other"];
export const SCORE_OPTIONS = [0, 1, 2, 3, 4, 5];

// All available UI themes.
export const PALETTES = {
  pink: {
    bg: "#fff8fb",
    bgSoft: "#fff3f8",
    bgGradientFrom: "#ffddea",
    bgGradientVia: "#f8abc7",
    bgGradientTo: "#bde0fe",
    card: "#ffffff",
    cardSoft: "#fff7fb",
    accent: "#e27396",
    accentSoft: "#f8abc7",
    accentMuted: "#ffddea",
    gradientEnd: "#bde0fe",
    accent2: "#a2d2ff",
    mint: "#eaf2d7",
    aqua: "#b3dee2",
    gradientMid: "#e9d1f0",
    emphasisEnd: "#cdb4db",
    accentEmphasis: "#880d1e",
    accentEmphasis2: "#3c096c",
    navy: "#3b3b6d",
    line: "#ead7e2",
    text: "#43384a",
    textSoft: "#6b6270",
    inputBorder: "#ecd6e0",
    cardBorder: "#f1dde7",
    innerCardBorder: "#efdee6",
    inputBg: "rgba(255,255,255,0.88)",
    controlBg: "rgba(255,255,255,0.86)",
    cardBg: "rgba(255,255,255,0.82)",
    surfaceBg: "rgba(255,255,255,0.78)",
    navBarBg: "rgba(255,255,255,0.8)",
    accentShadow: "rgba(226,115,150,0.2)",
    accentGlow: "rgba(226,115,150,0.35)",
    chartColors: [
      "#e27396",
      "#6ab5e8",
      "#42c0a8",
      "#f0a850",
      "#a07ad0",
      "#72bb80",
      "#e8826a",
      "#c472c8",
    ],
    chartHeatmapRgb: "226, 115, 150",
  },
  green: {
    bg: "#f6fbf8",
    bgSoft: "#eef8f2",
    bgGradientFrom: "#d4edda",
    bgGradientVia: "#a8d5b5",
    bgGradientTo: "#bde0fe",
    card: "#ffffff",
    cardSoft: "#f0fbf4",
    accent: "#5a9e72",
    accentSoft: "#90c7a4",
    accentMuted: "#d4edda",
    gradientEnd: "#bde0fe",
    accent2: "#a2d2ff",
    mint: "#eaf2d7",
    aqua: "#b3dee2",
    gradientMid: "#eff2d7",
    emphasisEnd: "#cdb4db",
    accentEmphasis: "#1a4a2c",
    accentEmphasis2: "#0d3320",
    navy: "#1a3a28",
    line: "#c8e6d0",
    text: "#2a3d2f",
    textSoft: "#4a6a55",
    inputBorder: "#c8e6d0",
    cardBorder: "#d4edda",
    innerCardBorder: "#c8e6d0",
    inputBg: "rgba(255,255,255,0.88)",
    controlBg: "rgba(255,255,255,0.86)",
    cardBg: "rgba(255,255,255,0.82)",
    surfaceBg: "rgba(255,255,255,0.78)",
    navBarBg: "rgba(255,255,255,0.8)",
    accentShadow: "rgba(90,158,114,0.2)",
    accentGlow: "rgba(90,158,114,0.35)",
    chartColors: [
      "#5a9e72",
      "#e06878",
      "#88c5db",
      "#d7c16a",
      "#6f79d0",
      "#b08bd8",
      "#f2a65a",
      "#d860c0",
    ],
    chartHeatmapRgb: "46, 125, 80",
    chartHeatmapAlphaBase: 0.12,
    chartHeatmapExponent: 1.45,
  },
  dark: {
    bg: "#0f0d1a",
    bgSoft: "#14112a",
    bgGradientFrom: "#1a1535",
    bgGradientVia: "#1e2d5a",
    bgGradientTo: "#0f1e3d",
    card: "#1a1535",
    cardSoft: "#1e1a3a",
    accent: "#8b7cf8",
    accentSoft: "#b4acfa",
    accentMuted: "#2d2852",
    gradientEnd: "#4a7cd4",
    accent2: "#6b9de8",
    mint: "#1e3a4a",
    aqua: "#2d5a7a",
    gradientMid: "#3d2d6a",
    emphasisEnd: "#5d4d9a",
    accentEmphasis: "#c7c2ff",
    accentEmphasis2: "#8b7cf8",
    navy: "#0a0d2a",
    line: "#2d2852",
    text: "#e8e3ff",
    textSoft: "#9d97c5",
    inputBorder: "#2d2852",
    cardBorder: "#2d2852",
    innerCardBorder: "#261f4a",
    inputBg: "rgba(20,17,42,0.88)",
    controlBg: "rgba(20,17,42,0.86)",
    cardBg: "rgba(20,17,42,0.82)",
    surfaceBg: "rgba(20,17,42,0.78)",
    navBarBg: "rgba(15,13,26,0.85)",
    accentShadow: "rgba(139,124,248,0.2)",
    accentGlow: "rgba(139,124,248,0.35)",
    chartColors: [
      "#8b7cf8",
      "#4a9fe8",
      "#3fb6b2",
      "#d6a657",
      "#c084fc",
      "#f472b6",
      "#7dd3fc",
      "#a3e635",
    ],
    chartHeatmapRgb: "167, 139, 250",
    chartHeatmapAlphaBase: 0.14,
    chartHeatmapExponent: 1.5,
  },
};

// Default palette alias kept for non-React modules (e.g. pdf-export.js).
export const PALETTE = PALETTES.pink;

// Semantic text scale. Spread into style objects or use directly as style prop.
export const TEXT = {
  caption:    { fontSize: "0.75rem",  lineHeight: "1rem"    },
  label:      { fontSize: "0.75rem",  lineHeight: "1rem",    fontWeight: "600" },
  input:      { fontSize: "0.8rem"                          },
  body:       { fontSize: "0.875rem", lineHeight: "1.25rem" },
  bodyStrong: { fontSize: "0.875rem", lineHeight: "1.25rem", fontWeight: "600" },
  base:       { fontSize: "1rem",     lineHeight: "1.5rem"  },
  title:      { fontSize: "1rem",     lineHeight: "1.5rem",  fontWeight: "600" },
  subheading: { fontSize: "1.125rem", lineHeight: "1.75rem", fontWeight: "700" },
  heading:    { fontSize: "1.5rem",   lineHeight: "2rem",    fontWeight: "700" },
};

// Generic colors for graphics.
export const CHART_COLORS = [
  "#e27396",
  "#6ab5e8",
  "#42c0a8",
  "#f0a850",
  "#a07ad0",
  "#72bb80",
  "#e8826a",
  "#c472c8",
];

// Gender-specific colors.
export const GENDER_COLORS = {
  male: "#7aa7ff",
  female: "#e27396",
  other: "#8fc9b5",
};

const MONTH_ABBR = {
  January: "Jan", February: "Feb", March: "Mar", April: "Apr",
  May: "May", June: "Jun", July: "Jul", August: "Aug",
  September: "Sep", October: "Oct", November: "Nov", December: "Dec",
  enero: "ene", febrero: "feb", marzo: "mar", abril: "abr",
  mayo: "may", junio: "jun", julio: "jul", agosto: "ago",
  septiembre: "sep", octubre: "oct", noviembre: "nov", diciembre: "dic",
};

export function abbreviateZodiacMonths(zodiacString) {
  return zodiacString.replace(
    /January|February|March|April|May|June|July|August|September|October|November|December|enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre/g,
    (m) => MONTH_ABBR[m],
  );
}

// Zodiac sign options by language. Aquarius
export const ZODIAC_OPTIONS = {
  en: [
    "♒ Aquarius (January 20 - February 19)",
    "♓ Pisces (February 20 - March 20)",
    "♈ Aries (March 21 - April 19)",
    "♉ Taurus (April 20 - May 20)",
    "♊ Gemini (May 21 - June 20)",
    "♋ Cancer (June 21 - July 22)",
    "♌ Leo (July 23 - August 23)",
    "♍ Virgo (August 24 - September 22)",
    "♎ Libra (September 23 - October 22)",
    "♏ Scorpio (October 23 - November 21)",
    "♐ Sagittarius (November 22 - December 21)",
    "♑ Capricorn (December 22 - January 19)",
  ],
  es: [
    "♒ Acuario (20 enero - 19 febrero)",
    "♓ Piscis (20 febrero - 20 marzo)",
    "♈ Aries (21 marzo - 19 abril)",
    "♉ Tauro (20 abril - 20 mayo)",
    "♊ Géminis (21 mayo - 20 junio)",
    "♋ Cáncer (21 junio - 22 julio)",
    "♌ Leo (23 julio - 23 agosto)",
    "♍ Virgo (24 agosto - 22 septiembre)",
    "♎ Libra (23 septiembre - 22 octubre)",
    "♏ Escorpio (23 octubre - 21 noviembre)",
    "♐ Sagitario (22 noviembre - 21 diciembre)",
    "♑ Capricornio (22 diciembre - 19 enero)",
  ],
};

/**
 * Detects the device/browser language and maps it to a supported app language.
 * Returns "es" if the primary language starts with "es", otherwise "en".
 */
export function detectDeviceLanguage() {
  const lang =
    (typeof navigator !== "undefined" &&
      (navigator.language || (navigator.languages && navigator.languages[0]))) ||
    "en";
  return lang.startsWith("es") ? "es" : "en";
}

// List of texts in the app, organized by language.
export const COPY = {
  en: {
    appTitle: "KissRecorder",
    heroTitle: "KissRecorder",
    peopleSaved: "People saved",
    totalEvents: "Total events",
    addNewPerson: "Add new person",
    viewEditPeople: "View and edit people",
    viewStatistics: "View statistics",
    clearLocalData: "Clear local data",
    clearLocalDataLabel: "Clear",
    exportJson: "Export data",
    exportJsonLabel: "Export",
    importJson: "Import data",
    importJsonLabel: "Import",
    dataSection: "Data",
    importJsonConfirmTitle: "Add imported data?",
    importJsonConfirmPeople: "people found in file",
    importJsonConfirmNew: "new people to add",
    importJsonConfirmSkipped: "already in your data (will be skipped)",
    importJsonConfirmAction: "Import",
    importJsonSuccessTitle: "Data imported",
    importJsonSuccessDesc: "people added to your data.",
    importJsonEmptyTitle: "No new people found",
    importJsonEmptyDesc: "All people in this file are already in your data.",
    importJsonErrorTypeTitle: "Invalid file type",
    importJsonErrorTypeDesc: "Please select a .json file.",
    importJsonErrorFormatTitle: "Invalid data format",
    importJsonErrorFormatDesc: "The file does not match the expected format. Make sure it was exported from KissRecorder.",
    exportJsonSuccessTitle: "Data exported",
    exportJsonSuccessWithWarningsTitle: "Exported with missing fields",
    exportJsonSuccessWithWarningsDesc: "Some required fields were missing and were exported as empty values.",
    exportJsonSavedAs: "Saved as",
    exportJsonLocationNative: "Saved to external storage",
    exportJsonLocationWeb: "Saved to your Downloads folder",
    exportJsonErrorTitle: "Export failed",
    exportJsonErrorDesc: "Something went wrong while exporting your data.",
    saveJsonErrorLog: "Save error log",
    exportPdf: "Export PDF",
    pdfReady: "Summary & statistics report",
    home: "Home",
    add: "Add",
    people: "People",
    stats: "Stats",
    name: "Name",
    age: "Age",
    gender: "Gender",
    howWeMet: "How we met",
    zodiacSign: "Zodiac sign",
    activity: "Activity",
    detail: "Specific",
    savePerson: "Save person",
    saveInfo: "Save info",
    cancel: "Cancel",
    back: "Back",
    editPerson: "Edit person",
    updateDetails: "Update personal details and save changes.",
    requiredName: "Name is required.",
    requiredAge: "Age is required.",
    validAge: "Use a valid age.",
    requiredGender: "Gender is required.",
    requiredHowWeMet: "How you met is required.",
    requiredZodiac: "Zodiac sign is required.",
    requiredActivity: "Activity is required.",
    select: "Select",
    none: "None",
    studies: "studies",
    works: "works",
    studiesWorks: "studies and works",
    other: "other",
    studiesForm: "study",
    worksForm: "work",
    studiesWorksForm: "study and work",
    male: "male",
    female: "female",
    personListTitle: "People",
    searchPlaceholder: "Search by name, detail, or event notes",
    filters: "Filters",
    refineList: "Filter list",
    filtersOrg: "Filters & organization",
    refineResults: "Refine results and reorganize the list.",
    ageRange: "Age range",
    min: "Min",
    max: "Max",
    allActivities: "All activities",
    allSigns: "All signs",
    groupBy: "Group by",
    sortBy: "Sort by",
    groupName: "Name",
    groupLastEvent: "Last event date",
    sortName: "Name",
    sortFirst: "First event date",
    sortLast: "Last event date",
    eventDateRange: "Event date range",
    dateFrom: "From",
    dateTo: "To",
    resetFilters: "Reset filters",
    showingResults: "Showing",
    result: "result",
    results: "results",
    noPeopleFound: "No people found",
    tryDifferent: "Try a different search term or reset your filters.",
    clearSearch: "Clear search",
    years: "years",
    met: "Met",
    events: "events",
    last: "Last",
    delete: "Delete",
    deletePerson: "Delete person",
    addEvent: "Add event",
    eventHistory: "Event history",
    tapEvent: "Tap an event to edit it quickly.",
    deleteAll: "Delete all",
    deleteAllEvents: "Delete all events",
    deleteAllEventsConfirmTitle: "Delete all events?",
    deleteAllEventsConfirmDesc: "This will permanently remove all events for this person. This action cannot be undone.",
    deleteAllEventsConfirmAction: "Yes, delete all",
    deletePersonConfirmTitle: "Delete this person?",
    deletePersonConfirmDesc: "This will permanently delete this person and all their events. This action cannot be undone.",
    deletePersonConfirmAction: "Yes, delete",
    noEventsYet: "No events recorded for this person yet.",
    noDetailsAdded: "No details added.",
    addEventTitle: "Add event",
    addEventDesc: "Record a new encounter.",
    editEventTitle: "Edit event",
    editEventDesc: "Update or remove this event.",
    eventDate: "Date",
    eventDetails: "Details",
    eventDetailsPlaceholder: "Optional context about the encounter",
    dateFormatHelper: "Required format: yyyy.MM.dd",
    validDateMsg: "Date must follow yyyy.MM.dd and be valid.",
    futureDateMsg: "Date cannot be in the future.",
    saveEvent: "Save event",
    deleteEvent: "Delete event",
    deleteEventConfirmTitle: "Delete this event?",
    deleteEventConfirmDesc: "This action cannot be undone.",
    deleteEventConfirmAction: "Yes, delete",
    analyticsTitle: "Summary & statistics",
    analyticsDesc: "Explore trends in a clean, wrapped-style overview.",
    avgEvents: "Average events / person",
    acrossAll: "Considering all people",
    topPerson: "Person with most events",
    topPersonPlural: "People with most events",
    tiedForTop: "at the top",
    eventsPerMonth: "Events per month",
    monthlyActivity: "Monthly encounter activity",
    eventsPerYear: "Events per year",
    yearlyTotals: "Yearly encounter totals",
    peopleMostEvents: "People with most events",
    topTracked: "Top tracked contacts",
    eventsByZodiac: "Events by zodiac sign",
    groupedBySign: "Total events grouped by sign",
    personsByZodiac: "People by zodiac sign",
    zodiacDistribution: "Distribution of people across signs",
    eventsByActivity: "Events by activity",
    groupedByActivity: "Total events grouped by person activity",
    personsByActivity: "People by activity",
    activityDistribution: "Distribution of people across activities",
    personsByGender: "People by gender",
    eventsByGender: "Events by gender",
    personsByAge: "People by age",
    personsByFirstLetter: "People by first letter",
    eventsByPersonCount: "People count by event count",
    multiYearPeople: "People with events in multiple years",
    noMultiYearPeopleYet: "No people with events in multiple years yet",
    dumbbellChart: "Presence by year",
    dumbbellDesc: "Years each person appears in — dots connected when consecutive",
    heatmapChart: "Activity heatmap",
    heatmapDesc: "Number of events per person per year",
    boxplotAgeRange: "Age range",
    noDataYet: "No data yet",
    chartEvent: "event",
    chartEvents: "events",
    chartPerson: "person",
    chartPersons: "people",
    chartYear: "year",
    langCode: "en",
    timelineTitle: "Events over time",
    personsTimelineTitle: "Persons over time",
    timelineAvg: "on average",
    timelineOn: "on",
    noPersons: "No persons",
    granWeek: "Week",
    granMonth: "Month",
    granYear: "Year",
    granHistoric: "Historic",
    language: "Language",
    settings: "Settings",
    viewOnboarding: "View tutorial",
    hideStats: "Hide stats",
    showStats: "Show stats",
    english: "English",
    spanish: "Español",
    iconColor: "Icon color",
    colorYellow: "Yellow",
    colorBlue: "Blue",
    colorPink: "Pink",
    colorPurple: "Purple",
    appTheme: "Theme",
    themePink: "Pink",
    themeGreen: "Green",
    themeDark: "Dark",
    noEvents: "No events",
    ungrouped: "Ungrouped",
    specificStudies: "What do you study?",
    specificWorks: "What do you do for work? If you studied something, mention what",
    specificStudiesWorks: "What do you study and what do you do for work?",
    optionalActivityDetails:
      "Optional details about activity, routine, or context",
    hiddenAccess: "Open app",
    missingEventDetailsBadge: "Needs detail",
    genderSplit: "People grouped by gender",
    eventsGenderSplit: "Total events grouped by gender",
    ageDistribution: "Each person's current age",
    ageCurrent: "Current age",
    ageAtEvent: "At event",
    ageAtEventDesc: "Each person's age when their event happened",
    firstLetterDist: "First-letter grouping",
    eventCountBuckets: "How many people have the same event count",
    multiYearDesc: "Count of people grouped by how many distinct years they appear in",
    multiYearTopTitle: "Top 3 · Most years",
    multiYearTopDesc: "People with events across the most distinct years",
    saveAndBack: "Save info",
    eventScore: "Rating",
    kiss: "kiss",
    kisses: "kisses",
    eventPlace: "Place",
    eventPlacePlaceholder: "Where did it happen?",
    eventSituation: "Situation",
    eventSituationPlaceholder: "What was the context?",
    eventObservations: "Observations",
    eventObservationsPlaceholder: "Optional additional notes",
    requiredPlace: "Place is required.",
    requiredSituation: "Situation is required.",
    situationTagsLabel: "Quick tags",
    addTag: "Add tag",
    newTagPlaceholder: "New tag...",
    addTagConfirm: "Add",
    scoredVsUnscored: "Rated vs unrated",
    scoredVsUnscoredDesc: "Share of events with a rating",
    scoreDistribution: "Rating distribution",
    scoreDistributionDesc: "Breakdown by rating level",
    averageScore: "Average rating / event",
    divideByYear: "Divide by year",
    showAllTogether: "Show all together",
    allYears: "All years",
    overview: "Overview",
    time: "Time",
    peopleStats: "People",
    profilesStats: "Profiles",
    scores: "Ratings",
    scoreOutOf: "out of 5💋",
    statsGroupOverview: "General summary",
    statsGroupTime: "Activity over time",
    statsGroupPeople: "Who appears most",
    statsGroupProfiles: "Profile and activity breakdowns",
    statsGroupScores: "Ratings",
    noScore: "No rating",
    reportGenerated: "Generated from KissRecorder",
    clearDataConfirmTitle: "Delete all data?",
    clearDataConfirmDesc:
      "This will permanently delete all saved people and events. This action cannot be undone.",
    clearDataConfirmAction: "Delete everything",
    pdfSuccessTitle: "PDF exported",
    pdfSuccessDesc: "Your report has been saved successfully.",
    pdfErrorTitle: "Export failed",
    pdfErrorDesc: "Something went wrong while generating the PDF.",
    pdfEmptyTitle: "No data to export",
    pdfEmptyDesc: "You need at least one person and one event to export statistics.",
    savePdfErrorLog: "Save error log",
    close: "Close",
    birthdayAlreadyHappened: "Has your birthday already happened this year?",
    birthdayAlreadyHappenedThird: "Has their birthday already happened this year?",
    birthdayYes: "Yes",
    birthdayNo: "Not yet",
    onboardingSkip: "Skip",
    onboardingNext: "Next",
    onboardingDone: "Get started",
    onboardingSlides: [
      {
        emoji: "💋",
        title: "Welcome",
        description: "Your private space to save and remember your most meaningful connections.",
      },
      {
        emoji: "👤",
        title: "Add people",
        description: "Save the name and a few details about each person that matters to you.",
      },
      {
        emoji: "📅",
        title: "Track moments",
        description: "Log the date, notes, and a score from 1 to 5 for each encounter.",
      },
      {
        emoji: "🔒",
        title: "Your privacy, always",
        description: "Everything stays on your device. No accounts, no cloud, no tracking.",
      },
      {
        type: "mockup",
        title: "Here's how to enter",
        description: "Tap the ♡ in the corner to open your space.",
      },
    ],
  },
  es: {
    appTitle: "KissRecorder",
    heroTitle: "KissRecorder",
    peopleSaved: "Personas guardadas",
    totalEvents: "Eventos totales",
    addNewPerson: "Agregar persona",
    viewEditPeople: "Ver y editar personas",
    viewStatistics: "Ver estadísticas",
    clearLocalData: "Borrar datos",
    clearLocalDataLabel: "Borrar",
    exportJson: "Exportar datos",
    exportJsonLabel: "Exportar",
    importJson: "Importar datos",
    importJsonLabel: "Importar",
    dataSection: "Datos",
    importJsonConfirmTitle: "¿Agregar datos importados?",
    importJsonConfirmPeople: "personas encontradas en el archivo",
    importJsonConfirmNew: "personas nuevas a agregar",
    importJsonConfirmSkipped: "ya están en tus datos (se omitirán)",
    importJsonConfirmAction: "Importar",
    importJsonSuccessTitle: "Datos importados",
    importJsonSuccessDesc: "personas agregadas a tus datos.",
    importJsonEmptyTitle: "Sin personas nuevas",
    importJsonEmptyDesc: "Todas las personas de este archivo ya están en tus datos.",
    importJsonErrorTypeTitle: "Tipo de archivo inválido",
    importJsonErrorTypeDesc: "Selecciona un archivo .json.",
    importJsonErrorFormatTitle: "Formato de datos inválido",
    importJsonErrorFormatDesc: "El archivo no coincide con el formato esperado. Asegúrate de que fue exportado desde KissRecorder.",
    exportJsonSuccessTitle: "Datos exportados",
    exportJsonSuccessWithWarningsTitle: "Exportado con campos faltantes",
    exportJsonSuccessWithWarningsDesc: "Algunos campos obligatorios faltaban y se exportaron como valores vacíos.",
    exportJsonSavedAs: "Guardado como",
    exportJsonLocationNative: "Guardado en almacenamiento externo",
    exportJsonLocationWeb: "Guardado en tu carpeta de Descargas",
    exportJsonErrorTitle: "Error al exportar",
    exportJsonErrorDesc: "Ocurrió un error al exportar los datos.",
    saveJsonErrorLog: "Guardar registro de error",
    exportPdf: "Exportar PDF",
    pdfReady: "Resumen y reporte de estadísticas",
    home: "Inicio",
    add: "Agregar",
    people: "Personas",
    stats: "Estadísticas",
    name: "Nombre",
    age: "Edad",
    gender: "Género",
    howWeMet: "Cómo nos conocimos",
    zodiacSign: "Signo zodiacal",
    activity: "Actividad",
    detail: "Específica",
    savePerson: "Guardar persona",
    saveInfo: "Guardar info",
    cancel: "Cancelar",
    back: "Volver",
    editPerson: "Editar persona",
    updateDetails: "Actualiza los datos personales y guarda los cambios.",
    requiredName: "El nombre es obligatorio.",
    requiredAge: "La edad es obligatoria.",
    validAge: "Usa una edad válida.",
    requiredGender: "El género es obligatorio.",
    requiredHowWeMet: "Cómo se conocieron es obligatorio.",
    requiredZodiac: "El signo zodiacal es obligatorio.",
    requiredActivity: "La actividad es obligatoria.",
    select: "Seleccionar",
    none: "Ninguno",
    studies: "estudia",
    works: "trabaja",
    studiesWorks: "estudia y trabaja",
    other: "otro",
    studiesForm: "estudio",
    worksForm: "trabajo",
    studiesWorksForm: "estudio y trabajo",
    male: "masculino",
    female: "femenino",
    personListTitle: "Personas",
    searchPlaceholder: "Buscar por nombre, detalle o notas de eventos",
    filters: "Filtros",
    refineList: "Filtrar lista",
    filtersOrg: "Filtros y organización",
    refineResults: "Refina resultados y reorganiza la lista.",
    ageRange: "Rango de edad",
    min: "Mín.",
    max: "Máx.",
    allActivities: "Todas las actividades",
    allSigns: "Todos los signos",
    groupBy: "Agrupar por",
    sortBy: "Ordenar por",
    groupName: "Nombre",
    groupLastEvent: "Último evento",
    sortName: "Nombre",
    sortFirst: "Primer evento",
    sortLast: "Último evento",
    eventDateRange: "Rango de fecha de eventos",
    dateFrom: "Desde",
    dateTo: "Hasta",
    resetFilters: "Restablecer filtros",
    showingResults: "Mostrando",
    result: "resultado",
    results: "resultados",
    noPeopleFound: "No se encontraron personas",
    tryDifferent: "Prueba otra búsqueda o restablece los filtros.",
    clearSearch: "Limpiar búsqueda",
    years: "años",
    met: "Nos conocimos",
    events: "eventos",
    last: "Último",
    delete: "Eliminar",
    deletePerson: "Eliminar persona",
    addEvent: "Agregar evento",
    eventHistory: "Historial de eventos",
    tapEvent: "Toca un evento para editarlo rápidamente.",
    deleteAll: "Eliminar todos",
    deleteAllEvents: "Eliminar todos los eventos",
    deleteAllEventsConfirmTitle: "¿Eliminar todos los eventos?",
    deleteAllEventsConfirmDesc: "Esto eliminará permanentemente todos los eventos de esta persona. Esta acción no se puede deshacer.",
    deleteAllEventsConfirmAction: "Sí, eliminar todos",
    deletePersonConfirmTitle: "¿Eliminar esta persona?",
    deletePersonConfirmDesc: "Esto eliminará permanentemente a esta persona y todos sus eventos. Esta acción no se puede deshacer.",
    deletePersonConfirmAction: "Sí, eliminar",
    noEventsYet: "Todavía no hay eventos registrados para esta persona.",
    noDetailsAdded: "No se añadieron detalles.",
    addEventTitle: "Agregar evento",
    addEventDesc: "Registra un nuevo encuentro.",
    editEventTitle: "Editar evento",
    editEventDesc: "Actualiza o elimina este evento.",
    eventDate: "Fecha",
    eventDetails: "Detalles",
    eventDetailsPlaceholder: "Contexto opcional sobre el encuentro",
    dateFormatHelper: "Formato obligatorio: yyyy.MM.dd",
    validDateMsg: "La fecha debe seguir el formato yyyy.MM.dd y ser válida.",
    futureDateMsg: "La fecha no puede ser futura.",
    saveEvent: "Guardar evento",
    deleteEvent: "Eliminar evento",
    deleteEventConfirmTitle: "¿Eliminar este evento?",
    deleteEventConfirmDesc: "Esta acción no se puede deshacer.",
    deleteEventConfirmAction: "Sí, eliminar",
    analyticsTitle: "Resumen y estadísticas",
    analyticsDesc:
      "Explora tendencias de tus encuentros en un resumen estilo wrapped.",
    avgEvents: "Promedio de eventos / persona",
    acrossAll: "Considerando todas las personas",
    topPerson: "Persona con más eventos",
    topPersonPlural: "Personas con más eventos",
    tiedForTop: "en el top",
    eventsPerMonth: "Eventos por mes",
    monthlyActivity: "Actividad mensual de encuentros",
    eventsPerYear: "Eventos por año",
    yearlyTotals: "Totales anuales de encuentros",
    peopleMostEvents: "Personas con más eventos",
    topTracked: "Contactos con más registros",
    eventsByZodiac: "Eventos por signo zodiacal",
    groupedBySign: "Eventos totales agrupados por signo",
    personsByZodiac: "Personas por signo zodiacal",
    zodiacDistribution: "Distribución de personas por signo",
    eventsByActivity: "Eventos por actividad",
    groupedByActivity: "Eventos totales agrupados por actividad",
    personsByActivity: "Personas por actividad",
    activityDistribution: "Distribución de personas por actividad",
    personsByGender: "Personas por género",
    eventsByGender: "Eventos por género",
    personsByAge: "Personas por edad",
    personsByFirstLetter: "Personas por inicial",
    eventsByPersonCount: "Cantidad de personas por cantidad de eventos",
    multiYearPeople: "Personas con eventos en múltiples años",
    noMultiYearPeopleYet:
      "Todavía no hay personas con eventos en múltiples años",
    dumbbellChart: "Presencia por año",
    dumbbellDesc: "Años en los que aparece cada persona — puntos unidos si son consecutivos",
    heatmapChart: "Mapa de actividad",
    heatmapDesc: "Cantidad de eventos por persona por año",
    boxplotAgeRange: "Rango de edades",
    noDataYet: "Todavía no hay datos",
    chartEvent: "evento",
    chartEvents: "eventos",
    chartPerson: "persona",
    chartPersons: "personas",
    chartYear: "año",
    langCode: "es",
    timelineTitle: "Eventos a lo largo del tiempo",
    personsTimelineTitle: "Personas a lo largo del tiempo",
    timelineAvg: "en promedio",
    timelineOn: "el",
    noPersons: "Sin personas",
    granWeek: "Semana",
    granMonth: "Mes",
    granYear: "Año",
    granHistoric: "Histórico",
    language: "Idioma",
    settings: "Configuración",
    viewOnboarding: "Ver tutorial",
    hideStats: "Ocultar estadísticas",
    showStats: "Mostrar estadísticas",
    english: "English",
    spanish: "Español",
    iconColor: "Color del ícono",
    colorYellow: "Amarillo",
    colorBlue: "Azul",
    colorPink: "Rosa",
    colorPurple: "Morado",
    appTheme: "Tema",
    themePink: "Rosa",
    themeGreen: "Verde",
    themeDark: "Oscuro",
    noEvents: "Sin eventos",
    ungrouped: "Sin grupo",
    specificStudies: "Qué estudias?",
    specificWorks: "En qué trabajas? Si estudiaste algo, menciona qué",
    specificStudiesWorks: "Qué estudias y en qué trabajas?",
    optionalActivityDetails:
      "Detalles opcionales sobre actividad, rutina o contexto",
    hiddenAccess: "Abrir app",
    missingEventDetailsBadge: "Falta detalle",
    genderSplit: "Personas agrupadas por género",
    eventsGenderSplit: "Eventos totales agrupados por género",
    ageDistribution: "Edad actual de cada persona",
    ageCurrent: "Edad actual",
    ageAtEvent: "Al evento",
    ageAtEventDesc: "Edad de cada persona cuando ocurrió su evento",
    firstLetterDist: "Agrupación por inicial",
    eventCountBuckets: "Cuántas personas tienen la misma cantidad de eventos",
    multiYearDesc: "Personas agrupadas por la cantidad de años distintos en los que aparecen",
    multiYearTopTitle: "Top 3 · Más años",
    multiYearTopDesc: "Personas con eventos en más años distintos",
    saveAndBack: "Guardar info",
    eventScore: "Calificación",
    kiss: "beso",
    kisses: "besos",
    eventPlace: "Lugar",
    eventPlacePlaceholder: "Dónde sucedió?",
    eventSituation: "Situación",
    eventSituationPlaceholder: "Cuál fue el contexto?",
    eventObservations: "Observaciones",
    eventObservationsPlaceholder: "Notas adicionales opcionales",
    requiredPlace: "El lugar es obligatorio.",
    requiredSituation: "La situación es obligatoria.",
    situationTagsLabel: "Etiquetas rápidas",
    addTag: "Agregar etiqueta",
    newTagPlaceholder: "Nueva etiqueta...",
    addTagConfirm: "Agregar",
    scoredVsUnscored: "Calificados vs sin calificar",
    scoredVsUnscoredDesc: "Proporción de eventos con calificación",
    scoreDistribution: "Distribución de calificaciones",
    scoreDistributionDesc: "Desglose por nivel de calificación",
    averageScore: "Promedio de calificación / evento",
    divideByYear: "Dividir por año",
    showAllTogether: "Mostrar todo junto",
    allYears: "Todos los años",
    overview: "Resumen",
    time: "Tiempo",
    peopleStats: "Personas",
    profilesStats: "Perfiles",
    scores: "Calificaciones",
    scoreOutOf: "de 5💋",
    statsGroupOverview: "Resumen general",
    statsGroupTime: "Actividad en el tiempo",
    statsGroupPeople: "Quién aparece más",
    statsGroupProfiles: "Distribuciones por perfil y actividad",
    statsGroupScores: "Calificaciones",
    noScore: "Sin calificación",
    reportGenerated: "Generado desde KissRecorder",
    clearDataConfirmTitle: "¿Eliminar todos los datos?",
    clearDataConfirmDesc:
      "Se eliminarán definitivamente todas las personas y eventos guardados. Esta acción no se puede deshacer.",
    clearDataConfirmAction: "Eliminar todo",
    pdfSuccessTitle: "PDF exportado",
    pdfSuccessDesc: "Tu informe se ha guardado correctamente.",
    pdfErrorTitle: "Error al exportar",
    pdfErrorDesc: "Ocurrió un error al generar el PDF.",
    pdfEmptyTitle: "Sin datos para exportar",
    pdfEmptyDesc: "Necesitas al menos una persona y un evento para exportar estadísticas.",
    savePdfErrorLog: "Guardar registro de error",
    close: "Cerrar",
    birthdayAlreadyHappened: "Ya estuviste de cumpleaños este año?",
    birthdayAlreadyHappenedThird: "¿Ya estuvo de cumpleaños este año?",
    birthdayYes: "Sí",
    birthdayNo: "Todavía no",
    onboardingSkip: "Omitir",
    onboardingNext: "Siguiente",
    onboardingDone: "Empezar",
    onboardingSlides: [
      {
        emoji: "💋",
        title: "Bienvenido/a",
        description: "Tu espacio privado para guardar y recordar tus conexiones más especiales.",
      },
      {
        emoji: "👤",
        title: "Agrega personas",
        description: "Guarda el nombre y algunos detalles de cada persona que importa.",
      },
      {
        emoji: "📅",
        title: "Registra momentos",
        description: "Anota la fecha, notas y una puntuación del 1 al 5 por cada encuentro.",
      },
      {
        emoji: "🔒",
        title: "Tu privacidad, siempre",
        description: "Todo se guarda en tu dispositivo. Sin cuentas, sin nube, sin rastreo.",
      },
      {
        type: "mockup",
        title: "Por aquí se entra",
        description: "Toca el ♡ en la esquina para abrir tu espacio.",
      },
    ],
  },
};
